### ISSUE TITLE
Rule Agreement

### ISSUE THREAD

**Issue by cloewen8** [cloewen8/CJ-Fan-Server-Bot#16]
Users must enter the random code provided by the bot at the end of the rules channel in order to use the server. This will confirm that users are aware of the rules before using the server.

- [x] Delete unmaintained notices (up to 2 messages back).
- [x] Create the code message.
- [x] Recreate the message once used (within a refresh time limit).
- [x] Listen for invite codes (approve users by giving them the `Little Fish` role).
- [x] Warn users who first join through a dm message.
- [x] Delete messages by unapproved users.
- [x] Disconnect unapproved users from voice channels.
- [x] Provide an unapproved verification channel.
- [x] Hide approved-only channels.

**Comment by ethanlaj** [comment]
On user join, change the code
When a user confirms the code, change the code again
Also, don’t put it right at the bottom, hide it in the middle of the rules somewhere

**Comment by cloewen8** [comment]
I like the idea for changing the code when it is used. I'd definitely need to limit how quickly it can change (encase multiple users join at the same time).
I don't want to split up the rules, if someone does not follow the agreement (I don't think I can either, a bot can't edit other peoples messages), they will be kicked.
